name: Github Actions - Push Template Basic
run-name: Running - ${{ github.event_name }}
on: 
  push:
    branches:
      - main
      - develop
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
            echo "comentario do workflow - branch"