name: Github Actions - Push Template Basic
run-name: Running - ${{ github.event_name }}
on: 
  push:
    branches:
      - main
      - develop
      - 'release/**'
jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentario
        run: |
            echo "comentario do workflow PUSH"