name: Github Actions - Push Template Basic
run-name: Running - ${{ github.event_name }}
on: 
  push:
    paths:
      - '**.txt'

jobs:
  on-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Comentario
        run: |
            echo "comentario do PUSH workflow  - Branch Path"

            